import Skyr/IAM

IAM.Policy({
	name: "public-org",
	subjects: ["Anonymous"],
	verbs: [
		"organization:View",
		"organization:ListRepositories",
	],
	objects: ["Constructs"],
})

IAM.Policy({
	name: "public-repos",
	subjects: ["Anonymous"],
	verbs: [
		"repository:View",
		"repository:ListEnvironments",
		"environment:View",
		"environment:ListResources",
		"resource:View",
	],
	objects: ["Constructs/*"],
})

IAM.Role({
	name: "ConstructPackage",
	description: "The deployment role for repositories that only contain constructs.",
})

let pusher = IAM.Role({
	name: "Pusher",
	description: "Can push to every repository in the organization.",
})

IAM.Policy({
	name: "push-all-repos",
	subjects: [pusher.qid],
	verbs: ["environment:Create", "environment:Push"],
	objects: ["Constructs/*"],
})

IAM.ServiceAccount({
	name: "GitHubActions",
	role: pusher.qid,
})
