import Skyr/IAM

IAM.Policy({
	name: "public-repos",
	subjects: ["Anonymous"],
	verbs: [
		"organization:View",
		"organization:ListRepositories",
		"repository:View",
		"repository:ListEnvironments",
		"environment:View",
		"environment:ListResources",
		"resource:View",
	],
	objects: ["Constructs/*"],
})

IAM.Role({
	name: "ConstructPackage",
	description: "The deployment role for repositories that only contain constructs.",
})
